const INGREDIENT_EMOJIS: Record<string, string> = {
  milk: "🥛",
  cheese: "🧀",
  egg: "🥚",
  eggs: "🥚",
  bread: "🍞",
  butter: "🧈",
  chicken: "🍗",
  beef: "🥩",
  pork: "🥓",
  bacon: "🥓",
  fish: "🐟",
  salmon: "🐟",
  rice: "🍚",
  pasta: "🍝",
  tomato: "🍅",
  tomatoes: "🍅",
  potato: "🥔",
  potatoes: "🥔",
  onion: "🧅",
  onions: "🧅",
  garlic: "🧄",
  carrot: "🥕",
  carrots: "🥕",
  apple: "🍎",
  apples: "🍎",
  banana: "🍌",
  bananas: "🍌",
  orange: "🍊",
  oranges: "🍊",
  lemon: "🍋",
  lemons: "🍋",
  strawberry: "🍓",
  strawberries: "🍓",
  grape: "🍇",
  grapes: "🍇",
  avocado: "🥑",
  avocadoes: "🥑",
  corn: "🌽",
  mushroom: "🍄",
  mushrooms: "🍄",
  pepper: "🫑",
  peppers: "🫑",
  chili: "🌶️",
  lettuce: "🥬",
  spinach: "🥬",
  broccoli: "🥦",
  cucumber: "🥒",
  pickle: "🥒",
  pickles: "🥒",
  olive: "🫒",
  olives: "🫒",
  peanut: "🥜",
  peanuts: "🥜",
  nut: "🥜",
  nuts: "🥜",
  almond: "🥜",
  almonds: "🥜",
  walnut: "🥜",
  walnuts: "🥜",
  honey: "🍯",
  sugar: "🧂",
  salt: "🧂",
  flour: "🌾",
  oat: "🌾",
  oats: "🌾",
  cereal: "🥣",
  yogurt: "🥛",
  cream: "🥛",
  coffee: "☕",
  tea: "🍵",
  water: "💧",
  juice: "🧃",
  wine: "🍷",
  beer: "🍺",
  chocolate: "🍫",
  cookie: "🍪",
  cookies: "🍪",
  cake: "🍰",
  pizza: "🍕",
  burger: "🍔",
  taco: "🌮",
  sushi: "🍣",
  shrimp: "🦐",
  crab: "🦀",
  soup: "🍲",
  stew: "🍲",
  bean: "🫘",
  beans: "🫘",
  lentil: "🫘",
  lentils: "🫘",
  tofu: "🧈",
  oil: "🫗",
  vinegar: "🫗",
  sauce: "🫙",
  ketchup: "🫙",
  mustard: "🫙",
  jam: "🫙",
  jelly: "🫙",
};

export function getIngredientEmoji(name: string): string {
  const normalized = name.toLowerCase().trim();

  if (INGREDIENT_EMOJIS[normalized]) {
    return INGREDIENT_EMOJIS[normalized];
  }

  for (const [keyword, emoji] of Object.entries(INGREDIENT_EMOJIS)) {
    if (normalized.includes(keyword)) {
      return emoji;
    }
  }

  return "🥫";
}
