import { writeFileSync } from "fs";

const templates = [
  ["Spaghetti Bolognese", "Classic Italian pasta with rich meat sauce.", "Italian", "Easy", 35, ["Spaghetti", "Beef Mince", "Tomatoes", "Onion", "Garlic", "Olive Oil"], ["400g", "500g", "400g", "1", "2 cloves", "2 tbsp"]],
  ["Lasagne", "Layered pasta bake with meat and cheese.", "Italian", "Medium", 60, ["Lasagne Sheets", "Beef Mince", "Tomatoes", "Milk", "Butter", "Flour", "Cheese"], ["250g", "500g", "400g", "500ml", "50g", "50g", "200g"]],
  ["Carbonara", "Creamy pasta with bacon and egg.", "Italian", "Easy", 25, ["Spaghetti", "Bacon", "Eggs", "Parmesan", "Black Pepper"], ["400g", "200g", "3", "100g", "1 tsp"]],
  ["Chicken Curry", "Mild chicken curry with rice.", "Indian", "Easy", 40, ["Chicken Breast", "Rice", "Onion", "Curry Powder", "Coconut Milk", "Tomatoes"], ["500g", "300g", "1", "2 tbsp", "400ml", "200g"]],
  ["Chicken Stir Fry", "Quick Asian-style stir fry.", "Asian", "Easy", 20, ["Chicken Breast", "Peppers", "Soy Sauce", "Rice", "Garlic", "Ginger"], ["400g", "2", "3 tbsp", "300g", "2 cloves", "1 inch"]],
  ["Chilli Con Carne", "Hearty beef and bean chilli.", "Mexican", "Easy", 45, ["Beef Mince", "Kidney Beans", "Tomatoes", "Onion", "Rice", "Cumin"], ["500g", "400g", "400g", "1", "300g", "1 tsp"]],
  ["Shepherd's Pie", "Lamb mince topped with mashed potato.", "British", "Medium", 50, ["Lamb Mince", "Potatoes", "Onion", "Carrots", "Stock", "Butter"], ["500g", "1kg", "1", "2", "500ml", "50g"]],
  ["Cottage Pie", "Beef mince topped with mashed potato.", "British", "Medium", 50, ["Beef Mince", "Potatoes", "Onion", "Carrots", "Stock", "Butter"], ["500g", "1kg", "1", "2", "500ml", "50g"]],
  ["Fish Pie", "Creamy fish and prawn pie with mash.", "British", "Medium", 55, ["White Fish", "Prawns", "Potatoes", "Milk", "Butter", "Peas"], ["400g", "200g", "1kg", "300ml", "50g", "150g"]],
  ["Roast Chicken", "Sunday roast with vegetables.", "British", "Medium", 90, ["Whole Chicken", "Potatoes", "Carrots", "Onion", "Oil", "Herbs"], ["1.5kg", "1kg", "4", "2", "3 tbsp", "2 tbsp"]],
  ["Chicken Alfredo", "Creamy pasta with chicken.", "Italian", "Easy", 30, ["Pasta", "Chicken Breast", "Cream", "Parmesan", "Garlic", "Butter"], ["400g", "400g", "200ml", "100g", "2 cloves", "30g"]],
  ["Tacos", "Mexican tacos with seasoned beef.", "Mexican", "Easy", 25, ["Tortillas", "Beef Mince", "Lettuce", "Tomatoes", "Cheese", "Sour Cream"], ["8", "400g", "1 head", "2", "150g", "100ml"]],
  ["Burritos", "Filled flour tortillas with rice and beans.", "Mexican", "Easy", 30, ["Tortillas", "Rice", "Kidney Beans", "Chicken Breast", "Cheese", "Salsa"], ["4", "200g", "400g", "300g", "100g", "100ml"]],
  ["Fajitas", "Sizzling chicken fajitas with peppers.", "Mexican", "Easy", 25, ["Chicken Breast", "Peppers", "Onion", "Tortillas", "Spices", "Lime"], ["400g", "3", "2", "6", "2 tbsp", "1"]],
  ["Mac & Cheese", "Creamy macaroni cheese bake.", "American", "Easy", 30, ["Macaroni", "Cheddar Cheese", "Milk", "Butter", "Flour"], ["400g", "300g", "500ml", "50g", "50g"]],
  ["Omelette", "Quick cheese and ham omelette.", "British", "Easy", 10, ["Eggs", "Cheese", "Ham", "Butter", "Milk"], ["3", "50g", "50g", "15g", "2 tbsp"]],
  ["Full English", "Traditional cooked breakfast.", "British", "Easy", 25, ["Eggs", "Bacon", "Sausages", "Baked Beans", "Tomatoes", "Mushrooms", "Bread"], ["2", "4 rashers", "2", "200g", "2", "100g", "2 slices"]],
  ["Tuna Pasta Bake", "Cheesy tuna pasta bake.", "British", "Easy", 35, ["Pasta", "Tuna", "Sweetcorn", "Milk", "Cheese", "Flour"], ["400g", "2 tins", "150g", "400ml", "200g", "50g"]],
  ["Fried Rice", "Chinese-style egg fried rice.", "Asian", "Easy", 20, ["Rice", "Eggs", "Peas", "Soy Sauce", "Spring Onion", "Oil"], ["300g", "2", "100g", "3 tbsp", "3", "2 tbsp"]],
  ["Sweet & Sour Chicken", "Crispy chicken in sweet and sour sauce.", "Chinese", "Medium", 35, ["Chicken Breast", "Peppers", "Pineapple", "Rice", "Soy Sauce", "Vinegar"], ["500g", "2", "200g", "300g", "3 tbsp", "2 tbsp"]],
  ["Thai Green Curry", "Fragrant Thai curry with coconut milk.", "Thai", "Medium", 35, ["Chicken Breast", "Green Curry Paste", "Coconut Milk", "Rice", "Aubergine", "Basil"], ["400g", "3 tbsp", "400ml", "300g", "1", "handful"]],
  ["Beef Stew", "Slow-cooked beef with vegetables.", "British", "Medium", 120, ["Beef", "Potatoes", "Carrots", "Onion", "Stock", "Flour"], ["600g", "500g", "3", "2", "500ml", "2 tbsp"]],
  ["Lamb Hotpot", "Layered lamb and potato hotpot.", "British", "Medium", 90, ["Lamb", "Potatoes", "Onion", "Stock", "Carrots", "Thyme"], ["500g", "800g", "2", "400ml", "2", "1 tsp"]],
  ["Toad in the Hole", "Sausages in Yorkshire pudding batter.", "British", "Medium", 45, ["Sausages", "Flour", "Eggs", "Milk", "Oil", "Onion Gravy"], ["8", "150g", "3", "300ml", "2 tbsp", "300ml"]],
  ["Chicken Kiev", "Breaded chicken with garlic butter.", "British", "Medium", 40, ["Chicken Breast", "Butter", "Garlic", "Breadcrumbs", "Parsley", "Oil"], ["4", "100g", "3 cloves", "150g", "2 tbsp", "for frying"]],
  ["Hunters Chicken", "Chicken with bacon, cheese and BBQ sauce.", "British", "Easy", 35, ["Chicken Breast", "Bacon", "Cheese", "BBQ Sauce", "Potatoes"], ["4", "8 rashers", "150g", "200ml", "600g"]],
  ["Jacket Potato", "Baked potato with fillings.", "British", "Easy", 60, ["Potatoes", "Butter", "Cheese", "Baked Beans", "Sour Cream"], ["4 large", "50g", "100g", "400g", "100ml"]],
  ["Caesar Salad", "Classic romaine salad with dressing.", "Salad", "Easy", 15, ["Lettuce", "Chicken Breast", "Parmesan", "Croutons", "Caesar Dressing"], ["1 head", "200g", "50g", "100g", "4 tbsp"]],
  ["Greek Salad", "Fresh Mediterranean salad.", "Salad", "Easy", 10, ["Cucumber", "Tomatoes", "Feta Cheese", "Olives", "Olive Oil", "Oregano"], ["1", "3", "150g", "100g", "3 tbsp", "1 tsp"]],
  ["Pizza", "Homemade margherita pizza.", "Italian", "Medium", 40, ["Pizza Dough", "Tomatoes", "Mozzarella", "Basil", "Olive Oil"], ["1 base", "200g", "200g", "handful", "2 tbsp"]],
  ["Risotto", "Creamy mushroom risotto.", "Italian", "Medium", 35, ["Arborio Rice", "Mushrooms", "Stock", "Onion", "Parmesan", "White Wine"], ["300g", "300g", "1L", "1", "100g", "150ml"]],
  ["Beef Tacos", "Seasoned beef tacos with fresh toppings.", "Mexican", "Easy", 20, ["Beef Mince", "Tortillas", "Lettuce", "Tomatoes", "Cheese"], ["400g", "8", "1 head", "2", "100g"]],
  ["Pork Stir Fry", "Quick pork and vegetable stir fry.", "Asian", "Easy", 20, ["Pork", "Peppers", "Soy Sauce", "Ginger", "Garlic", "Rice"], ["400g", "2", "3 tbsp", "1 inch", "2 cloves", "300g"]],
  ["Salmon Teriyaki", "Glazed salmon with rice.", "Asian", "Easy", 25, ["Salmon", "Soy Sauce", "Honey", "Rice", "Broccoli", "Sesame Seeds"], ["4 fillets", "4 tbsp", "2 tbsp", "300g", "200g", "1 tbsp"]],
  ["Vegetable Curry", "Mild mixed vegetable curry.", "Indian", "Easy", 30, ["Potatoes", "Cauliflower", "Peas", "Coconut Milk", "Curry Powder", "Rice"], ["2", "1 head", "150g", "400ml", "2 tbsp", "300g"]],
  ["Mushroom Risotto", "Earthy mushroom risotto.", "Italian", "Medium", 35, ["Arborio Rice", "Mushrooms", "Stock", "Onion", "Parmesan", "Butter"], ["300g", "400g", "1L", "1", "100g", "50g"]],
  ["Chicken Noodle Soup", "Comforting chicken soup.", "British", "Easy", 40, ["Chicken", "Noodles", "Carrots", "Celery", "Onion", "Stock"], ["300g", "200g", "2", "2 sticks", "1", "1L"]],
  ["Beef Burgers", "Homemade beef burgers with buns.", "American", "Easy", 25, ["Beef Mince", "Burger Buns", "Lettuce", "Tomatoes", "Cheese", "Onion"], ["500g", "4", "4 leaves", "2", "4 slices", "1"]],
  ["Chicken Wraps", "Grilled chicken wraps with salad.", "American", "Easy", 20, ["Chicken Breast", "Wraps", "Lettuce", "Tomatoes", "Mayonnaise"], ["400g", "4", "1 head", "2", "3 tbsp"]],
  ["Prawn Cocktail", "Classic starter with Marie Rose sauce.", "British", "Easy", 15, ["Prawns", "Lettuce", "Mayonnaise", "Ketchup", "Lemon"], ["300g", "1 head", "3 tbsp", "1 tbsp", "1"]],
  ["Scampi and Chips", "Breaded scampi with chips.", "British", "Easy", 25, ["Scampi", "Potatoes", "Peas", "Tartare Sauce", "Oil"], ["400g", "600g", "150g", "4 tbsp", "for frying"]],
  ["Sausage and Mash", "Bangers and mash with onion gravy.", "British", "Easy", 30, ["Sausages", "Potatoes", "Onion", "Stock", "Butter", "Milk"], ["8", "1kg", "2", "300ml", "50g", "100ml"]],
  ["Corned Beef Hash", "Pan-fried corned beef and potato.", "British", "Easy", 25, ["Corned Beef", "Potatoes", "Onion", "Eggs", "Oil"], ["340g", "500g", "1", "2", "2 tbsp"]],
  ["Ham and Pea Soup", "Thick split pea soup with ham.", "British", "Easy", 45, ["Split Peas", "Ham", "Onion", "Carrots", "Stock"], ["300g", "200g", "1", "2", "1L"]],
  ["Leek and Potato Soup", "Creamy leek and potato soup.", "British", "Easy", 35, ["Leeks", "Potatoes", "Stock", "Cream", "Butter", "Onion"], ["4", "500g", "1L", "100ml", "30g", "1"]],
  ["Minestrone", "Italian vegetable soup.", "Italian", "Easy", 40, ["Pasta", "Tomatoes", "Beans", "Carrots", "Celery", "Stock"], ["150g", "400g", "400g", "2", "2 sticks", "1L"]],
  ["Tomato Soup", "Simple homemade tomato soup.", "British", "Easy", 25, ["Tomatoes", "Onion", "Stock", "Cream", "Basil", "Garlic"], ["800g", "1", "500ml", "100ml", "handful", "2 cloves"]],
  ["French Onion Soup", "Caramelised onion soup with cheese.", "French", "Medium", 50, ["Onions", "Beef Stock", "Bread", "Gruyere Cheese", "Butter", "Thyme"], ["6", "1L", "4 slices", "150g", "50g", "1 tsp"]],
  ["Beef Stir Fry", "Quick beef and vegetable stir fry.", "Asian", "Easy", 20, ["Beef", "Peppers", "Soy Sauce", "Garlic", "Ginger", "Rice"], ["400g", "2", "3 tbsp", "2 cloves", "1 inch", "300g"]],
  ["Pork Chops", "Pan-fried pork chops with apple.", "British", "Easy", 25, ["Pork Chops", "Apples", "Onion", "Thyme", "Butter", "Potatoes"], ["4", "2", "1", "1 tsp", "30g", "600g"]],
  ["Lamb Chops", "Grilled lamb chops with mint.", "British", "Medium", 30, ["Lamb Chops", "Mint", "Potatoes", "Peas", "Garlic", "Oil"], ["4", "handful", "600g", "150g", "2 cloves", "2 tbsp"]],
  ["Steak and Chips", "Pan-seared steak with homemade chips.", "British", "Easy", 35, ["Steak", "Potatoes", "Butter", "Garlic", "Oil", "Pepper"], ["2", "600g", "30g", "2 cloves", "for frying", "to taste"]],
  ["Chicken Parmesan", "Breaded chicken with tomato and cheese.", "Italian", "Medium", 40, ["Chicken Breast", "Tomatoes", "Mozzarella", "Parmesan", "Breadcrumbs", "Pasta"], ["4", "400g", "200g", "100g", "150g", "400g"]],
  ["Penne Arrabiata", "Spicy tomato pasta.", "Italian", "Easy", 20, ["Penne", "Tomatoes", "Garlic", "Chilli", "Olive Oil", "Parsley"], ["400g", "400g", "3 cloves", "1", "2 tbsp", "handful"]],
  ["Pesto Pasta", "Basil pesto pasta with pine nuts.", "Italian", "Easy", 15, ["Pasta", "Pesto", "Parmesan", "Pine Nuts", "Olive Oil"], ["400g", "4 tbsp", "50g", "30g", "1 tbsp"]],
  ["Gnocchi Bake", "Baked gnocchi in tomato sauce.", "Italian", "Easy", 30, ["Gnocchi", "Tomatoes", "Mozzarella", "Basil", "Cream"], ["500g", "400g", "200g", "handful", "100ml"]],
  ["Seafood Paella", "Spanish rice with seafood.", "Spanish", "Hard", 50, ["Rice", "Prawns", "Mussels", "Peppers", "Saffron", "Stock"], ["300g", "200g", "300g", "2", "pinch", "600ml"]],
  ["Chicken Paella", "Spanish chicken and rice dish.", "Spanish", "Medium", 45, ["Rice", "Chicken Thighs", "Peppers", "Peas", "Saffron", "Stock"], ["300g", "500g", "2", "150g", "pinch", "600ml"]],
  ["Beef Enchiladas", "Baked tortillas with beef and sauce.", "Mexican", "Medium", 40, ["Tortillas", "Beef Mince", "Enchilada Sauce", "Cheese", "Onion", "Sour Cream"], ["6", "400g", "400ml", "200g", "1", "100ml"]],
  ["Chicken Quesadillas", "Cheesy chicken folded tortillas.", "Mexican", "Easy", 20, ["Tortillas", "Chicken Breast", "Cheese", "Peppers", "Salsa"], ["4", "300g", "200g", "2", "100ml"]],
  ["Nachos", "Loaded nachos with cheese and salsa.", "Mexican", "Easy", 15, ["Tortilla Chips", "Cheese", "Salsa", "Sour Cream", "Jalapenos", "Beef Mince"], ["200g", "200g", "150ml", "100ml", "50g", "200g"]],
  ["Pulled Pork", "Slow-cooked shredded pork.", "American", "Hard", 240, ["Pork Shoulder", "BBQ Sauce", "Onion", "Garlic", "Coleslaw", "Burger Buns"], ["1kg", "300ml", "2", "4 cloves", "200g", "6"]],
  ["BBQ Ribs", "Sticky barbecue pork ribs.", "American", "Hard", 180, ["Pork Ribs", "BBQ Sauce", "Brown Sugar", "Garlic", "Paprika", "Coleslaw"], ["1kg", "300ml", "2 tbsp", "3 cloves", "1 tbsp", "200g"]],
  ["Meatballs", "Italian meatballs in tomato sauce.", "Italian", "Medium", 40, ["Beef Mince", "Breadcrumbs", "Egg", "Tomatoes", "Pasta", "Parmesan"], ["500g", "100g", "1", "400g", "400g", "50g"]],
  ["Stuffed Peppers", "Rice and mince stuffed peppers.", "Mediterranean", "Medium", 45, ["Peppers", "Beef Mince", "Rice", "Tomatoes", "Onion", "Cheese"], ["4", "400g", "200g", "200g", "1", "100g"]],
  ["Stuffed Aubergine", "Mediterranean stuffed aubergine.", "Mediterranean", "Medium", 50, ["Aubergine", "Lamb Mince", "Tomatoes", "Onion", "Couscous", "Feta Cheese"], ["2", "300g", "200g", "1", "150g", "100g"]],
  ["Shakshuka", "Eggs poached in spiced tomato sauce.", "Middle Eastern", "Easy", 25, ["Eggs", "Tomatoes", "Peppers", "Onion", "Cumin", "Bread"], ["4", "400g", "2", "1", "1 tsp", "4 slices"]],
  ["Falafel Wrap", "Crispy falafel in flatbread.", "Middle Eastern", "Medium", 35, ["Chickpeas", "Flatbread", "Lettuce", "Tomatoes", "Tahini", "Cumin"], ["400g", "4", "1 head", "2", "3 tbsp", "1 tsp"]],
  ["Hummus Bowl", "Chickpea hummus with vegetables.", "Middle Eastern", "Easy", 15, ["Chickpeas", "Tahini", "Lemon", "Garlic", "Olive Oil", "Pitta Bread"], ["400g", "3 tbsp", "1", "2 cloves", "3 tbsp", "4"]],
  ["Butter Chicken", "Creamy Indian butter chicken.", "Indian", "Medium", 40, ["Chicken Breast", "Tomatoes", "Cream", "Butter", "Garam Masala", "Rice"], ["500g", "400g", "200ml", "50g", "2 tbsp", "300g"]],
  ["Chicken Tikka Masala", "Popular creamy tikka masala.", "Indian", "Medium", 45, ["Chicken Breast", "Yogurt", "Tomatoes", "Cream", "Spices", "Rice"], ["500g", "150ml", "400g", "200ml", "2 tbsp", "300g"]],
  ["Lamb Rogan Josh", "Aromatic Kashmiri lamb curry.", "Indian", "Hard", 90, ["Lamb", "Yogurt", "Tomatoes", "Onion", "Spices", "Rice"], ["600g", "150ml", "400g", "2", "2 tbsp", "300g"]],
  ["Vegetable Biryani", "Fragrant spiced rice with vegetables.", "Indian", "Medium", 50, ["Rice", "Mixed Vegetables", "Yogurt", "Spices", "Onion", "Stock"], ["300g", "400g", "100ml", "2 tbsp", "2", "500ml"]],
  ["Pad Thai", "Thai stir-fried noodles.", "Thai", "Medium", 30, ["Rice Noodles", "Prawns", "Eggs", "Bean Sprouts", "Peanuts", "Lime"], ["200g", "200g", "2", "150g", "50g", "1"]],
  ["Chicken Satay", "Grilled chicken with peanut sauce.", "Thai", "Medium", 35, ["Chicken Breast", "Peanut Butter", "Soy Sauce", "Lime", "Coconut Milk", "Rice"], ["400g", "3 tbsp", "2 tbsp", "1", "100ml", "300g"]],
  ["Tom Yum Soup", "Hot and sour Thai soup.", "Thai", "Medium", 25, ["Prawns", "Lemongrass", "Lime", "Mushrooms", "Chilli", "Stock"], ["200g", "2 stalks", "1", "150g", "2", "600ml"]],
  ["Katsu Curry", "Japanese breaded chicken curry.", "Japanese", "Medium", 40, ["Chicken Breast", "Rice", "Curry Sauce", "Breadcrumbs", "Flour", "Eggs"], ["400g", "300g", "1 pack", "150g", "50g", "2"]],
  ["Teriyaki Salmon Bowl", "Salmon rice bowl with vegetables.", "Japanese", "Easy", 25, ["Salmon", "Rice", "Broccoli", "Soy Sauce", "Sesame Seeds", "Spring Onion"], ["2 fillets", "300g", "200g", "3 tbsp", "1 tbsp", "3"]],
  ["Ramen", "Japanese noodle soup.", "Japanese", "Medium", 35, ["Ramen Noodles", "Pork", "Eggs", "Spring Onion", "Soy Sauce", "Stock"], ["2 packs", "200g", "2", "4", "3 tbsp", "800ml"]],
  ["Bibimbap", "Korean rice bowl with vegetables.", "Korean", "Medium", 35, ["Rice", "Beef", "Eggs", "Spinach", "Carrots", "Soy Sauce"], ["300g", "200g", "2", "100g", "2", "3 tbsp"]],
  ["Bulgogi", "Korean marinated beef.", "Korean", "Medium", 30, ["Beef", "Soy Sauce", "Sugar", "Garlic", "Sesame Oil", "Rice"], ["400g", "4 tbsp", "2 tbsp", "3 cloves", "1 tbsp", "300g"]],
  ["Dumplings", "Pan-fried pork dumplings.", "Chinese", "Hard", 60, ["Pork Mince", "Dumpling Wrappers", "Cabbage", "Soy Sauce", "Ginger", "Garlic"], ["300g", "30", "200g", "3 tbsp", "1 inch", "2 cloves"]],
  ["Kung Pao Chicken", "Spicy Sichuan chicken stir fry.", "Chinese", "Medium", 30, ["Chicken Breast", "Peanuts", "Peppers", "Soy Sauce", "Chilli", "Rice"], ["400g", "50g", "2", "3 tbsp", "2", "300g"]],
  ["Beef Chow Mein", "Stir-fried noodles with beef.", "Chinese", "Easy", 25, ["Egg Noodles", "Beef", "Cabbage", "Soy Sauce", "Spring Onion", "Oil"], ["300g", "300g", "200g", "3 tbsp", "4", "2 tbsp"]],
  ["Egg Fried Noodles", "Quick egg noodle stir fry.", "Chinese", "Easy", 15, ["Egg Noodles", "Eggs", "Soy Sauce", "Spring Onion", "Oil", "Vegetables"], ["300g", "2", "3 tbsp", "3", "2 tbsp", "200g"]],
  ["Quiche Lorraine", "Bacon and cheese quiche.", "French", "Medium", 50, ["Shortcrust Pastry", "Bacon", "Eggs", "Cream", "Cheese", "Nutmeg"], ["1 sheet", "200g", "4", "200ml", "100g", "pinch"]],
  ["Croque Monsieur", "French ham and cheese sandwich.", "French", "Easy", 15, ["Bread", "Ham", "Gruyere Cheese", "Butter", "Flour", "Milk"], ["4 slices", "8 slices", "150g", "30g", "20g", "200ml"]],
  ["Ratatouille", "Provençal vegetable stew.", "French", "Medium", 45, ["Aubergine", "Courgette", "Tomatoes", "Peppers", "Onion", "Garlic"], ["1", "2", "400g", "2", "1", "3 cloves"]],
  ["Coq au Vin", "Chicken braised in wine.", "French", "Hard", 90, ["Chicken Thighs", "Red Wine", "Bacon", "Mushrooms", "Onion", "Stock"], ["6", "500ml", "150g", "200g", "2", "400ml"]],
  ["Beef Bourguignon", "Slow-cooked beef in red wine.", "French", "Hard", 180, ["Beef", "Red Wine", "Bacon", "Mushrooms", "Onion", "Stock"], ["800g", "500ml", "150g", "200g", "2", "500ml"]],
  ["Crepes", "Thin French pancakes.", "French", "Easy", 20, ["Flour", "Eggs", "Milk", "Butter", "Sugar", "Lemon"], ["150g", "3", "300ml", "30g", "2 tbsp", "1"]],
  ["Waffles", "Crispy breakfast waffles.", "American", "Easy", 20, ["Flour", "Eggs", "Milk", "Butter", "Sugar", "Baking Powder"], ["200g", "2", "300ml", "50g", "2 tbsp", "2 tsp"]],
  ["Pancakes", "Fluffy American pancakes.", "American", "Easy", 15, ["Flour", "Eggs", "Milk", "Butter", "Sugar", "Baking Powder"], ["200g", "2", "300ml", "30g", "2 tbsp", "2 tsp"]],
  ["French Toast", "Cinnamon eggy bread.", "American", "Easy", 15, ["Bread", "Eggs", "Milk", "Cinnamon", "Butter", "Maple Syrup"], ["6 slices", "3", "200ml", "1 tsp", "30g", "4 tbsp"]],
  ["Club Sandwich", "Triple-decker chicken sandwich.", "American", "Easy", 15, ["Bread", "Chicken Breast", "Bacon", "Lettuce", "Tomatoes", "Mayonnaise"], ["6 slices", "200g", "4 rashers", "4 leaves", "2", "3 tbsp"]],
  ["BLT Sandwich", "Bacon lettuce and tomato sandwich.", "American", "Easy", 10, ["Bread", "Bacon", "Lettuce", "Tomatoes", "Mayonnaise"], ["4 slices", "6 rashers", "4 leaves", "2", "2 tbsp"]],
  ["Tuna Sandwich", "Classic tuna mayo sandwich.", "British", "Easy", 10, ["Bread", "Tuna", "Mayonnaise", "Sweetcorn", "Lettuce"], ["4 slices", "2 tins", "3 tbsp", "50g", "4 leaves"]],
  ["Egg Mayo Sandwich", "Simple egg mayonnaise sandwich.", "British", "Easy", 10, ["Bread", "Eggs", "Mayonnaise", "Cress", "Butter"], ["4 slices", "4", "3 tbsp", "handful", "20g"]],
  ["Chicken Salad Sandwich", "Light chicken salad sandwich.", "British", "Easy", 10, ["Bread", "Chicken Breast", "Mayonnaise", "Celery", "Lettuce"], ["4 slices", "200g", "3 tbsp", "2 sticks", "4 leaves"]],
  ["Vegetable Soup", "Hearty mixed vegetable soup.", "British", "Easy", 35, ["Carrots", "Potatoes", "Celery", "Onion", "Stock", "Tomatoes"], ["3", "2", "3 sticks", "1", "1L", "200g"]],
  ["Chicken Casserole", "One-pot chicken and vegetable bake.", "British", "Easy", 60, ["Chicken Thighs", "Potatoes", "Carrots", "Onion", "Stock", "Thyme"], ["6", "500g", "3", "2", "500ml", "1 tsp"]],
  ["Sausage Casserole", "Sausage and bean casserole.", "British", "Easy", 45, ["Sausages", "Baked Beans", "Onion", "Tomatoes", "Peppers", "Stock"], ["8", "400g", "2", "200g", "2", "300ml"]],
  ["Beef Casserole", "Slow-cooked beef casserole.", "British", "Medium", 90, ["Beef", "Potatoes", "Carrots", "Onion", "Stock", "Flour"], ["600g", "500g", "3", "2", "500ml", "2 tbsp"]],
  ["Fish and Chips", "Classic battered fish with chips.", "British", "Medium", 40, ["White Fish", "Potatoes", "Flour", "Beer", "Peas", "Oil"], ["600g", "800g", "200g", "200ml", "150g", "for frying"]],
  ["Kedgeree", "Smoked fish rice with eggs.", "British", "Medium", 35, ["Smoked Haddock", "Rice", "Eggs", "Butter", "Curry Powder", "Parsley"], ["400g", "300g", "3", "50g", "1 tsp", "handful"]],
  ["Bubble and Squeak", "Fried potato and cabbage cakes.", "British", "Easy", 25, ["Potatoes", "Cabbage", "Bacon", "Butter", "Onion"], ["500g", "300g", "100g", "30g", "1"]],
  ["Cornish Pasty", "Traditional meat and potato pasty.", "British", "Hard", 60, ["Shortcrust Pastry", "Beef", "Potatoes", "Swede", "Onion", "Egg"], ["500g", "300g", "200g", "150g", "1", "1 for wash"]],
  ["Ploughman's Lunch", "Cheese, pickle and bread platter.", "British", "Easy", 10, ["Cheddar Cheese", "Bread", "Pickle", "Apple", "Ham", "Lettuce"], ["200g", "4 slices", "3 tbsp", "1", "100g", "4 leaves"]],
  ["Scotch Eggs", "Sausage-wrapped boiled eggs.", "British", "Hard", 45, ["Eggs", "Sausage Meat", "Breadcrumbs", "Flour", "Oil"], ["6", "400g", "150g", "50g", "for frying"]],
  ["Pork Pie", "Traditional British pork pie.", "British", "Hard", 120, ["Pork", "Hot Water Crust Pastry", "Stock", "Egg", "Pepper"], ["500g", "400g", "200ml", "1", "to taste"]],
  ["Beef Wellington", "Beef fillet in puff pastry.", "British", "Hard", 90, ["Beef Fillet", "Puff Pastry", "Mushrooms", "Prosciutto", "Eggs", "Mustard"], ["600g", "500g", "300g", "6 slices", "1", "2 tbsp"]],
  ["Yorkshire Puddings", "Classic roast dinner yorkshires.", "British", "Medium", 30, ["Flour", "Eggs", "Milk", "Oil", "Salt"], ["150g", "3", "300ml", "for tin", "pinch"]],
  ["Bread and Butter Pudding", "Classic baked bread pudding.", "British", "Easy", 45, ["Bread", "Butter", "Milk", "Eggs", "Sugar", "Raisins"], ["8 slices", "50g", "400ml", "3", "50g", "100g"]],
  ["Apple Crumble", "Baked apple dessert with crumble.", "British", "Easy", 40, ["Apples", "Flour", "Butter", "Sugar", "Cinnamon", "Oats"], ["6", "150g", "100g", "100g", "1 tsp", "50g"]],
  ["Banoffee Pie", "Banana and toffee pie.", "British", "Medium", 40, ["Bananas", "Condensed Milk", "Cream", "Biscuits", "Butter"], ["4", "400g", "300ml", "200g", "80g"]],
  ["Eton Mess", "Strawberries, cream and meringue.", "British", "Easy", 15, ["Strawberries", "Cream", "Meringue", "Sugar"], ["300g", "200ml", "100g", "2 tbsp"]],
  ["Trifle", "Layered sponge and custard dessert.", "British", "Easy", 30, ["Sponge Cake", "Custard", "Cream", "Fruit", "Jelly"], ["200g", "400ml", "200ml", "200g", "1 pack"]],
];

const recipes = templates.map((t, i) => ({
  id: `recipe-${String(i + 1).padStart(3, "0")}`,
  name: t[0],
  description: t[1],
  category: t[2],
  difficulty: t[3],
  prep_time: t[4],
  ingredients: t[5],
  typical_quantities: t[6],
  image: null,
}));

const output = `import type { Recipe } from "@/types/recipes";

export const BUILTIN_RECIPES: Recipe[] = ${JSON.stringify(recipes, null, 2)};
`;

writeFileSync("src/data/recipes.ts", output);
console.log(`Generated ${recipes.length} recipes`);
